project_id = "dxuusnodizfpqcrakwkc"

[functions.cloudinary-upload]
verify_jwt = false

[functions.cloudinary-upload.env]
CLOUDINARY_CLOUD_NAME = "CLOUDINARY_CLOUD_NAME"
CLOUDINARY_API_KEY = "CLOUDINARY_API_KEY"
CLOUDINARY_API_SECRET = "CLOUDINARY_API_SECRET"